--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MoonlightNetwork/MiniGameAPI
build-by-default: true
branches:
- master
projects:
  MiniGameAPI:
    path: ""
    model: virion
    type: library
...
